blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/kozandlov/avito-python-sdk/blob/main/docs/USAGE.md
    about: Проверьте документацию перед созданием issue.
